const router = require('express').Router();
const { getProducts, getProduct, createProduct, updateProduct, deleteProduct, getFeatured } = require('../controllers/productController');
const { protect, admin } = require('../middleware/auth');
router.get('/', getProducts);
router.get('/featured', getFeatured);
router.get('/:id', getProduct);
router.post('/', protect, admin, createProduct);
router.put('/:id', protect, admin, updateProduct);
router.delete('/:id', protect, admin, deleteProduct);
module.exports = router;
